# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChurchBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('giving', models.IntegerField(default=0)),
                ('earned', models.IntegerField(default=0)),
                ('staff', models.IntegerField(default=0)),
                ('operations', models.IntegerField(default=0)),
                ('ministry', models.IntegerField(default=0)),
                ('outreach', models.IntegerField(default=0)),
                ('church', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Church')),
            ],
        ),
        migrations.CreateModel(
            name='ChurchEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('participants', models.IntegerField(default=1)),
                ('duration', models.IntegerField(default=1)),
                ('date', models.DateField()),
                ('leadership', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ChurchScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('connect_hours', models.IntegerField(default=0)),
                ('connect_score', models.IntegerField(default=0)),
                ('lead_hours', models.IntegerField(default=0)),
                ('lead_score', models.IntegerField(default=0)),
                ('give_dollars', models.IntegerField(default=0)),
                ('give_score', models.IntegerField(default=0)),
                ('invest_difference', models.IntegerField(default=0)),
                ('invest_score', models.IntegerField(default=0)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.Church')),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.Church')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='churchevent',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='church.ChurchScore'),
        ),
        migrations.AddField(
            model_name='churchbudget',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='church.ChurchScore'),
        ),
    ]
