# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_budgetcategories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BudgetCategories',
            new_name='BudgetCategory',
        ),
    ]
