# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchbudget',
            name='church',
        ),
        migrations.RemoveField(
            model_name='churchbudget',
            name='score',
        ),
        migrations.RemoveField(
            model_name='churchevent',
            name='score',
        ),
        migrations.RemoveField(
            model_name='churchscore',
            name='church',
        ),
        migrations.DeleteModel(
            name='ChurchBudget',
        ),
        migrations.DeleteModel(
            name='ChurchEvent',
        ),
        migrations.DeleteModel(
            name='ChurchScore',
        ),
    ]
