# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-11 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_auto_20170815_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('giving', models.IntegerField(default=0)),
                ('rent', models.IntegerField(default=0)),
                ('staff', models.IntegerField(default=0)),
                ('operations', models.IntegerField(default=0)),
                ('ministry', models.IntegerField(default=0)),
                ('building', models.IntegerField(default=0)),
            ],
        ),
    ]
