# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-11 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='mortgage',
            field=models.IntegerField(default=0),
        ),
    ]
