# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-11 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0007_money_mortgage'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='other_revenue',
            field=models.IntegerField(default=0),
        ),
    ]
