# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 19:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0008_money_other_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='month',
            field=models.CharField(choices=[('2017-10', '2017-10'), ('2017-11', '2017-11'), ('2017-12', '2017-12')], default='2018-01', max_length=10),
        ),
        migrations.AlterField(
            model_name='money',
            name='building',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)]),
        ),
        migrations.AlterField(
            model_name='money',
            name='giving',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)]),
        ),
        migrations.AlterField(
            model_name='money',
            name='ministry',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)]),
        ),
        migrations.AlterField(
            model_name='money',
            name='mortgage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)]),
        ),
        migrations.AlterField(
            model_name='money',
            name='operations',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)]),
        ),
        migrations.AlterField(
            model_name='money',
            name='other_revenue',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)]),
        ),
        migrations.AlterField(
            model_name='money',
            name='rent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)]),
        ),
        migrations.AlterField(
            model_name='money',
            name='staff',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)]),
        ),
    ]
