# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0011_auto_20171221_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='month',
            field=models.CharField(choices=[('2017-10', '2017-10'), ('2017-11', '2017-11'), ('2017-12', '2017-12')], default='2018-01', max_length=10, unique=True),
        ),
    ]
