# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 22:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0013_remove_money_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='designated',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)]),
        ),
        migrations.AlterField(
            model_name='money',
            name='month',
            field=models.CharField(choices=[('2018-01', '2018-01'), ('2018-02', '2018-02')], max_length=10, unique=True),
        ),
    ]
