# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0014_auto_20171228_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='mortgage',
        ),
    ]
