# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 00:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0015_remove_money_mortgage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='giving',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)], verbose_name='Excessive Giving'),
        ),
    ]
