# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 00:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0016_auto_20180107_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='building',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)], verbose_name='Other Income'),
        ),
        migrations.AlterField(
            model_name='money',
            name='designated',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)], verbose_name='Designated Giving'),
        ),
        migrations.AlterField(
            model_name='money',
            name='giving',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)], verbose_name='Regular Giving'),
        ),
        migrations.AlterField(
            model_name='money',
            name='ministry',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)], verbose_name='Ministry'),
        ),
        migrations.AlterField(
            model_name='money',
            name='month',
            field=models.CharField(choices=[('2018-01', '2018-01'), ('2018-02', '2018-02'), ('2018-03', '2018-03')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='money',
            name='operations',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)], verbose_name='Operations'),
        ),
        migrations.AlterField(
            model_name='money',
            name='other_revenue',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)], verbose_name='Improvements'),
        ),
        migrations.AlterField(
            model_name='money',
            name='rent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)], verbose_name='Rental Income'),
        ),
        migrations.AlterField(
            model_name='money',
            name='staff',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)], verbose_name='Staff'),
        ),
    ]
