# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='client',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
