# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0002_auto_20170404_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mybook.Author'),
        ),
    ]
