# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikidoc',
            name='body',
            field=models.TextField(default='No Body Text'),
        ),
    ]
