# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 18:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_wikidoc_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikidoc',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wikidoc',
            name='path',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='wikidoc',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='WikiUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
