# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-25 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0002_aspect_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='age',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='aspect',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='life.Aspect'),
        ),
    ]
