# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-25 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
    ]
