# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(editable=False)),
                ('score', models.IntegerField()),
                ('designer', models.CharField(max_length=20)),
                ('reviewer', models.CharField(max_length=20)),
                ('notes', models.TextField()),
            ],
        ),
    ]
