# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewscore',
            name='date',
            field=models.DateTimeField(editable=False),
        ),
    ]
