# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 00:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0003_auto_20171107_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('score', models.IntegerField()),
                ('designer', models.CharField(choices=[('adam5160', 'adam5160'), ('adel4571', 'adel4571'), ('bell1486', 'bell1486'), ('butl5737', 'butl5737'), ('carl2159', 'carl2159'), ('carl9668', 'carl9668'), ('carr4666', 'carr4666'), ('casp2764', 'casp2764'), ('cruz3674', 'cruz3674'), ('cutl7614', 'cutl7614'), ('drur4653', 'drur4653'), ('enge7698', 'enge7698'), ('espi0784', 'espi0784'), ('feas4242', 'feas4242'), ('hans9131', 'hans9131'), ('harm4214', 'harm4214'), ('here9018', 'here9018'), ('hern6661', 'hern6661'), ('herr9858', 'herr9858'), ('kaup6567', 'kaup6567'), ('kell7133', 'kell7133'), ('lang8151', 'lang8151'), ('lous9442', 'lous9442'), ('marq6695', 'marq6695'), ('mate2933', 'mate2933'), ('mena7788', 'mena7788'), ('milt0773', 'milt0773'), ('moni2990', 'moni2990'), ('mont0846', 'mont0846'), ('mull9451', 'mull9451'), ('orti8903', 'orti8903'), ('pani2679', 'pani2679'), ('rist4093', 'rist4093'), ('shie5673', 'shie5673'), ('shin8899', 'shin8899'), ('simo8137', 'simo8137'), ('stre7262', 'stre7262'), ('tutt7678', 'tutt7678'), ('weav8611', 'weav8611')], max_length=20)),
                ('reviewer', models.CharField(choices=[('adam5160', 'adam5160'), ('adel4571', 'adel4571'), ('bell1486', 'bell1486'), ('butl5737', 'butl5737'), ('carl2159', 'carl2159'), ('carl9668', 'carl9668'), ('carr4666', 'carr4666'), ('casp2764', 'casp2764'), ('cruz3674', 'cruz3674'), ('cutl7614', 'cutl7614'), ('drur4653', 'drur4653'), ('enge7698', 'enge7698'), ('espi0784', 'espi0784'), ('feas4242', 'feas4242'), ('hans9131', 'hans9131'), ('harm4214', 'harm4214'), ('here9018', 'here9018'), ('hern6661', 'hern6661'), ('herr9858', 'herr9858'), ('kaup6567', 'kaup6567'), ('kell7133', 'kell7133'), ('lang8151', 'lang8151'), ('lous9442', 'lous9442'), ('marq6695', 'marq6695'), ('mate2933', 'mate2933'), ('mena7788', 'mena7788'), ('milt0773', 'milt0773'), ('moni2990', 'moni2990'), ('mont0846', 'mont0846'), ('mull9451', 'mull9451'), ('orti8903', 'orti8903'), ('pani2679', 'pani2679'), ('rist4093', 'rist4093'), ('shie5673', 'shie5673'), ('shin8899', 'shin8899'), ('simo8137', 'simo8137'), ('stre7262', 'stre7262'), ('tutt7678', 'tutt7678'), ('weav8611', 'weav8611')], max_length=20)),
                ('notes', models.TextField(validators=[django.core.validators.MinLengthValidator(500)])),
            ],
        ),
        migrations.AlterField(
            model_name='reviewscore',
            name='designer',
            field=models.CharField(choices=[('adam5160', 'adam5160'), ('adel4571', 'adel4571'), ('bell1486', 'bell1486'), ('butl5737', 'butl5737'), ('carl2159', 'carl2159'), ('carl9668', 'carl9668'), ('carr4666', 'carr4666'), ('casp2764', 'casp2764'), ('cruz3674', 'cruz3674'), ('cutl7614', 'cutl7614'), ('drur4653', 'drur4653'), ('enge7698', 'enge7698'), ('espi0784', 'espi0784'), ('feas4242', 'feas4242'), ('hans9131', 'hans9131'), ('harm4214', 'harm4214'), ('here9018', 'here9018'), ('hern6661', 'hern6661'), ('herr9858', 'herr9858'), ('kaup6567', 'kaup6567'), ('kell7133', 'kell7133'), ('lang8151', 'lang8151'), ('lous9442', 'lous9442'), ('marq6695', 'marq6695'), ('mate2933', 'mate2933'), ('mena7788', 'mena7788'), ('milt0773', 'milt0773'), ('moni2990', 'moni2990'), ('mont0846', 'mont0846'), ('mull9451', 'mull9451'), ('orti8903', 'orti8903'), ('pani2679', 'pani2679'), ('rist4093', 'rist4093'), ('shie5673', 'shie5673'), ('shin8899', 'shin8899'), ('simo8137', 'simo8137'), ('stre7262', 'stre7262'), ('tutt7678', 'tutt7678'), ('weav8611', 'weav8611')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewscore',
            name='notes',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='reviewscore',
            name='reviewer',
            field=models.CharField(choices=[('adam5160', 'adam5160'), ('adel4571', 'adel4571'), ('bell1486', 'bell1486'), ('butl5737', 'butl5737'), ('carl2159', 'carl2159'), ('carl9668', 'carl9668'), ('carr4666', 'carr4666'), ('casp2764', 'casp2764'), ('cruz3674', 'cruz3674'), ('cutl7614', 'cutl7614'), ('drur4653', 'drur4653'), ('enge7698', 'enge7698'), ('espi0784', 'espi0784'), ('feas4242', 'feas4242'), ('hans9131', 'hans9131'), ('harm4214', 'harm4214'), ('here9018', 'here9018'), ('hern6661', 'hern6661'), ('herr9858', 'herr9858'), ('kaup6567', 'kaup6567'), ('kell7133', 'kell7133'), ('lang8151', 'lang8151'), ('lous9442', 'lous9442'), ('marq6695', 'marq6695'), ('mate2933', 'mate2933'), ('mena7788', 'mena7788'), ('milt0773', 'milt0773'), ('moni2990', 'moni2990'), ('mont0846', 'mont0846'), ('mull9451', 'mull9451'), ('orti8903', 'orti8903'), ('pani2679', 'pani2679'), ('rist4093', 'rist4093'), ('shie5673', 'shie5673'), ('shin8899', 'shin8899'), ('simo8137', 'simo8137'), ('stre7262', 'stre7262'), ('tutt7678', 'tutt7678'), ('weav8611', 'weav8611')], max_length=20),
        ),
    ]
