# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0004_auto_20171112_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewerscore',
            name='notes',
            field=models.TextField(),
        ),
    ]
