# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-09 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0005_auto_20171221_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='reviewerscore',
            name='designer',
            field=models.CharField(choices=[('', '')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewerscore',
            name='reviewer',
            field=models.CharField(choices=[('', '')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewscore',
            name='designer',
            field=models.CharField(choices=[('', '')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewscore',
            name='reviewer',
            field=models.CharField(choices=[('', '')], max_length=20),
        ),
    ]
