# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-09 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0008_student_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(editable=False, max_length=100)),
                ('page', models.CharField(editable=False, max_length=100)),
                ('score', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('requirement_1', models.BooleanField()),
                ('requirement_2', models.BooleanField()),
                ('reviewer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='unc.Student')),
            ],
        ),
        migrations.AlterField(
            model_name='reviewerscore',
            name='designer',
            field=models.CharField(choices=[('Curly', 'Curly'), ('Larry', 'Larry'), ('Moe', 'Moe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewerscore',
            name='reviewer',
            field=models.CharField(choices=[('Curly', 'Curly'), ('Larry', 'Larry'), ('Moe', 'Moe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewscore',
            name='designer',
            field=models.CharField(choices=[('Curly', 'Curly'), ('Larry', 'Larry'), ('Moe', 'Moe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewscore',
            name='reviewer',
            field=models.CharField(choices=[('Curly', 'Curly'), ('Larry', 'Larry'), ('Moe', 'Moe')], max_length=20),
        ),
    ]
