# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-09 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0009_auto_20181009_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='requirement_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='requirement_2',
            field=models.BooleanField(default=False),
        ),
    ]
