# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-09 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0010_auto_20181009_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='requirement_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='requirement_4',
            field=models.BooleanField(default=False),
        ),
    ]
