# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-09 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0011_auto_20181009_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='requirement_10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='requirement_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='requirement_6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='requirement_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='requirement_8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='requirement_9',
            field=models.BooleanField(default=False),
        ),
    ]
