# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-09 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0012_auto_20181009_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='designer',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='designer', to='unc.Student'),
        ),
    ]
