# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-09 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0013_review_designer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='domain',
        ),
    ]
