# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-09 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0014_remove_review_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=-1),
        ),
    ]
