# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-11 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0016_review_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='due',
            field=models.DateTimeField(default='2018-09-01', editable=False),
        ),
        migrations.AddField(
            model_name='student',
            name='designer_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='student',
            name='reviewer_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='notes',
            field=models.TextField(default='You must type a summary of problems.'),
        ),
    ]
