# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_thotbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='thot',
            name='thotbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.ThotBook'),
        ),
    ]
