# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_thotbook_rootid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thotbook',
            name='rootid',
            field=models.IntegerField(default=0),
        ),
    ]
