# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_auto_20170619_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thotbook',
            name='rootid',
        ),
    ]
