# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_remove_thotbook_rootid'),
    ]

    operations = [
        migrations.AddField(
            model_name='thotbook',
            name='rootid',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
