# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0009_auto_20170630_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cumulative',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='money',
            name='category',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='workshop.Category'),
        ),
    ]
