# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aspire', '0002_auto_20170410_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='aspire.Goal')),
                ('project', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='aspire.Project')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='organization',
            field=models.CharField(default='Human Race', max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='client',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='aspire.Client'),
        ),
    ]
