# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aspire', '0003_auto_20170414_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='project',
        ),
        migrations.AlterField(
            model_name='goal',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aspire.Goal'),
        ),
    ]
